### ISSUE TITLE
Should the image styles be configured to allow [ left, full, right ]?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-build-decoupled-document#10]
By default, the image style feature enables `[ full, side ]` styles. This approach is not necessarily the best for the "document editor" where more visual features appear. So, perhaps, this build should be configured to `[ left, full, right ]` instead?

WDYT❓

**Comment by fredck** [comment]
It makes sense for me.

**Comment by wwalc** [comment]
What with aligning the image to center?

**Comment by Reinmar** [comment]
Dunno... no opinion. Would make it complete. But would also make the image toolbar look bad :D
