### ISSUE TITLE
Decoupled editor README.md has outdated API

### ISSUE THREAD

**Issue by ConnorSinnott** [ckeditor/ckeditor5-build-decoupled-document#23]
## Is this a bug report or feature request?

🐞 Bug report

## 💻 Version of CKEditor

CKEditor v5 @ 12.4.0

## 📋 Steps to reproduce

Current [README.md](https://github.com/ckeditor/ckeditor5-build-decoupled-document/blob/09f0f1b2550cc7c2f00b55f911c36d78eb8a17eb/README.md) has following snippets:

```html
<div id="editor">
	<p>This is the editor content.</p>
</div>
<script src="./node_modules/@ckeditor/ckeditor5-build-decoupled-document/build/ckeditor.js"></script>
<script>
	DecoupledEditor
		.create( '<h2>Hello world!</h2>', {
			toolbarContainer: document.querySelector( '.toolbar-container' ),
			editableContainer: document.querySelector( '.editable-container' )
		} )
		.then( editor => {
			window.editor = editor;
		} )
		.catch( err => {
			console.error( err.stack );
		} );
</script>
```

and

```js
import DecoupledEditor from '@ckeditor/ckeditor5-build-decoupled-document';

// Or using the CommonJS version:
// const DecoupledEditor = require( '@ckeditor/ckeditor5-build-decoupled-document' );

DecoupledEditor
	.create( '<h2>Hello world!</h2>', {
		toolbarContainer: document.querySelector( '.toolbar-container' ),
		editableContainer: document.querySelector( '.editable-container' )
	} )
	.then( editor => {
		window.editor = editor;
	} )
	.catch( err => {
		console.error( err.stack );
	} );
```

## ✅ Expected result

Used API should be up to date.

## ❎ Actual result

Both of listings use wrong APIs, `config.toolbarContainer` and `config.editableContainer` were removed some time ago.

Also it doesn't make sense in the first example to preset content to something and then override it completely different string using `DecoupledEditor.create`.

**Comment by ConnorSinnott** [comment]
I thought it was strange that within the example, content was defined both within the div being replaced as well as in the editors initialization. In the end the code below worked for me. Is the recommended? 

```javascript
CKEditor
    .create(document.querySelector('.editable-container'))
    .then((editor) => {
        const toolbarContainer = document.querySelector('.toolbar-container');

        if (toolbarContainer)
            toolbarContainer.appendChild(editor.ui.view.toolbar.element);
    }).catch(...);
```

**Comment by mlewand** [comment]
Thanks for reporting @ConnorSinnott.

Theoretically it would work, but as you pointed out it's kind of useless as the value will be overridden during editor initialization. It can cause confusion and I agree that it should be changed - thanks for that.

Actually got heavily outdated as not that long ago both `toolbarContainer` and `editableContainer` properties of editor.create config were removed 🙈

We'll make sure to change it during this iteration.
