### ISSUE TITLE
Use ckeditor 5 with react

### ISSUE THREAD

**Issue by boychamhoctoanlyanh** [ckeditor/ckeditor5-build-decoupled-document#4]
How can i use ckeditor upload images

**Comment by Reinmar** [comment]
Check this regarding image upload: https://docs.ckeditor.com/ckeditor5/latest/features/image-upload.html

And this regarding React: https://github.com/ckeditor/ckeditor5/issues/599

**Comment by boychamhoctoanlyanh** [comment]
How can i upload images to firebase sir
