### ISSUE TITLE
The export name should follow the creator name

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-build-decoupled-document#6]
Right now, the build exposes a global variable called `DecoupledDocumentEditor`. This name is then used in the documentation, but it links to `DecoupledEditor`'s docs.

This is confusing. Especially that in the human-readable form we call this build the "document editor build".

Therefore, I think that the editor class should always follow the creator name. In this case, it'd be `DecoupledEditor`.

This isn't perfect, because, again, we call this the "document editor build". Unfortunately, this was impossible to avoid once we decided to call the build after "document" and the editor after "decoupled".

What if we'll create `@ckeditor/ckeditor5-build-classic-document` in the future? Then, we'll call the exported value the `ClassicEditor`.

Won't it conflict with `@ckeditor/ckeditor5-build-classic`? No, because you should never have two builds of the same editor on one page. Actually, you should not have two builds of any editors on the same page.

Why not calling the variable `DocumentEditor`? Because editor creators have different APIs and when looking at this name you should be able to figure out how to use it so you need to be able to find its docs in the API docs.

How we'll differentiate `@ckeditor/ckeditor5-build-classic-document` and `@ckeditor/ckeditor5-build-decoupled-document` when using human-readable names? Most likely we'll name them as "Document editor build (with the classic UI)" and "Document editor build (with the decoupled UI)".

cc @AnnaTomanek @wwalc

**Comment by wwalc** [comment]
> Won't it conflict with @ckeditor/ckeditor5-build-classic? No, because you should never have two builds of the same editor on one page. Actually, you should not have two builds of any editors on the same page.

Suppose that i want to have a document editor and in the bottom right window a chat window, which is run by a (at least visually) a completely different editor. It would be quite intuitive to make it using two editors, for better features separation, different release cycles etc. Especially if the chat editor is reused on different pages where the document editor is not used (e.g. for live support etc.). So I do not agree with that point.

In any case it seems that exporting `DecoupledEditor` is a fair tradeoff for having the API docs less confusing. Even if it's limiting. But in such rare cases one will most likely create own builds any way and will have the possibility to easily change the exported module name.

**Comment by AnnaTomanek** [comment]
Sounds reasonable to me, at least as far as I can understand it :D

**Comment by Reinmar** [comment]
> Suppose that i want to have a document editor and in the bottom right window a chat window, which is run by a (at least visually) a completely different editor. It would be quite intuitive to make it using two editors, for better features separation, different release cycles etc. Especially if the chat editor is reused on different pages where the document editor is not used (e.g. for live support etc.). So I do not agree with that point.

I agree. But you know that it creates a huge bloat in terms of code size and added stylesheets? Also, loading two conflicting stylesheets may results in errors. In such a case, [superbuilds](https://github.com/ckeditor/ckeditor5/issues/923) or integrating the editors directly into your app is much better and safer solution. This will result in a shared code between these two builds (~40-45% reduced code size), shared CSS, no conflicts, etc.
